### ISSUE TITLE
Modifying forward config file location

### ISSUE THREAD

**Issue by jaxxstorm** [voxpupuli/puppet-unbound#129]
I'm trying to set up unbound with a different config file location.

My hiera config:

```
unbound::val_permissive_mode: true # Disable DNSSec
unbound::chroot: true
unbound::confdir: "/var/unbound"
unbound::config_file: "/var/unbound/unbound.conf"
unbound::runtime_dir: "/var/unbound"
unbound::interfaces:
  - '127.0.0.1'
unbound::access:
  - '127.0.0.1'
unbound::custom_server_conf:
  - 'cache-max-ttl: 7200'
  - 'cache-max-negative-ttl: 1'
```

However catalog compilation fails:

```
# puppet agent -t --environment=unbound --server=tukd-puppet-1.dapt.to
Info: Retrieving pluginfacts
Info: Retrieving plugin
Notice: /File[/var/lib/puppet/lib/puppet/parser/functions/validate_unbound_addr.rb]/ensure: defined content as '{md5}468519a15b83e2f5a9f2de6ffb221546'
Notice: /File[/var/lib/puppet/lib/puppet_x/unbound]/ensure: created
Notice: /File[/var/lib/puppet/lib/puppet_x/unbound/validate_addrs.rb]/ensure: defined content as '{md5}4d0719572d4d086d61cd7cbb69f0b693'
Info: Loading facts
Info: Caching catalog for hostname
Error: Failed to apply catalog: Could not find dependent Exec[concat_/etc/unbound/unbound.conf] for File[/var/lib/puppet/concat/_etc_unbound_unbound.conf/fragments/20_unbound-forward-.] at /etc/puppet/environments/unbound/modules/concat/manifests/fragment.pp:136
```

What isn't clear to me is why `/etc/unbound/unbound.conf` is still even a thing? Which param do I need to set here?

**Comment by jaxxstorm** [comment]
Just realised this is because we have to set the config file in the forward definition, doesn't look like it's inheriting from params correctly?

**Comment by jaxxstorm** [comment]
So even if I override the config file like so:

```
unbound::forward:
  '.':
    forward_first: 'yes'
    config_file: "/var/unbound/conf.d/global_forward.conf"
    address:
```

Same issue.

**Comment by xaque208** [comment]
I believe this issue is caused by the `forward` class using the data from the `params` class causing whatever setting on the `unbound::config_file` to be ignored.  So it seems that it is not possible to override the config location, even though it looks like we aimed to do so.  The later issue setting the `config_file` on the `unbound::forward` resources, there is no corresponding `concat` resource for the fragment, so it never gets created.  So yes, this needs a fix.

**Comment by b4ldr** [comment]
unbound::forward now uses `$config_file = $unbound::config_file` so this should now work as expected, please reopen with update information if you still see an issue
