### ISSUE TITLE
unbound-checkconf fails on first-time configuration (pid dir is missing)

### ISSUE THREAD

**Issue by dekimsey** [voxpupuli/puppet-unbound#188]
The unbound-checkconf is unable to validate the pid file directory during first-run. This is because the epel unbound initrc creates /var/run/unbound at daemon start time.

There is a [bugzilla](https://bugzilla.redhat.com/show_bug.cgi?id=1226668) about the issue. I happen to find the issue on both RHEL5 and RHEL6 machines. RHEL7 did not exhibit the issue.

```
Error: Execution of '/usr/sbin/unbound-checkconf /etc/unbound/unbound.conf20181105-56517-13c6j0h' returned 1: /var/run/unbound: No such file or directory
[1541453860] unbound-checkconf[57038:0] fatal error: pidfile directory does not exist
Error: /Stage[main]/Unbound/Concat[/etc/unbound/unbound.conf]/File[/etc/unbound/unbound.conf]/content: change from {md5}b89d00e77d575b7154c2487f31192ef0 to {md5}b0987114fd303bbfeaaa6027b04b8f3e failed: Execution of '/usr/sbin/unbound-checkconf /etc/unbound/unbound.conf20181105-56517-13c6j0h' returned 1: /var/run/unbound: No such file or directory
[1541453860] unbound-checkconf[57038:0] fatal error: pidfile directory does not exist
Notice: /Stage[main]/Unbound/Service[unbound]: Dependency File[/etc/unbound/unbound.conf] has failures: true
```

The fix is simply to create the directory if it doesn't exist before running the configuration.
```
exec { '/usr/bin/install -v --mode=755 --owner=unbound --group=unbound -d /var/run/unbound':
    onlyif => '/usr/bin/test ! -d /var/run/unbound',
    before => Concat[/etc/unbound/unbound.conf],
    require => Package[unbound],
}
```

**Comment by xaque208** [comment]
Thank you for the report.  Do I understand correctly that only the RHEL7 EPEL package creates the directory the first time around?  I don't have any RHEL to test your suggested fix, but it seems reasonable.  Probably worth wrapping that in a condition for the platform, but I can't be certain that this issue is not present on other platforms.

**Comment by dekimsey** [comment]
Agreed, I think this is a platform-specific issue for RHEL <= 6. The RHEL7 package handles this gracefully. I haven't looked as to how. My guess is systemd is creating the pidfile directory or it isn't using one at all.

**Comment by b4ldr** [comment]
the pid dir should be created [here](https://github.com/xaque208/puppet-unbound/blob/master/manifests/init.pp#L200)

**Comment by b4ldr** [comment]
pretty sure this is fixed now but please reopen if its still an issue
