### ISSUE TITLE
commit 5868593634371290ad013e4a3005f25cb8d7e1fe broke the module for me

### ISSUE THREAD

**Issue by buzzdeee** [voxpupuli/puppet-unbound#221]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: puppet-5.5.16
- Ruby: ruby-2.6.5
- Distribution: OpenBSD 6.6-current
- Module version: git revision 5868593634371290ad013e4a3005f25cb8d7e1fe

## What are you seeing
Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Evaluation Error: Resource type not found: Unix::Path (file: /etc/puppetlabs/code/environments/production/modules/unbound/manifests/stub.pp, line: 35, column: 3) on node
## What behaviour did you expect instead
should just work 
## Any additional information you'd like to impart
seems git commit 5868593634371290ad013e4a3005f25cb8d7e1fe introduced Unix::Path 

where is that supposed to come from? looking at metadata.json, I see stdlib and concat, stdlib is at git revision ee1f0551e7564a15d85ef879eb1e83595388abd2 (metadata.json says 6.2.0), should be fine, and I guess Unix::Path doesn't come from concat.

**Comment by buzzdeee** [comment]
removing the Unix::Path from stub.pp, it fails then with:

Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Evaluation Error: Error while evaluating a Resource Statement, Evaluation Error: Error while evaluating a Function Call, Failed to parse template unbound/stub.erb:
  Filepath: /etc/puppetlabs/code/environments/production/modules/unbound/templates/stub.erb
  Line: 4
  Detail: uninitialized constant Puppet::Parser::TemplateWrapper::PuppetX
Did you mean?  Puppet_X
               PuppetDB
               Puppet::Parser::TemplateWrapper::Puppetdb
 (file: /etc/puppetlabs/code/environments/production/modules/unbound/manifests/stub.pp, line: 41, column: 16) (file: /etc/puppetlabs/code/environments/production/modules/profile/manifests/dnsserver.pp, line: 35) on node mynode
Warning: Not using cache on failed catalog
Error: Could not retrieve catalog; skipping run

**Comment by xaque208** [comment]
Hmm, it looks like the path reference should be `Stdlib::Unixpath` I suspect.  I'll test the latest in my environment sometime soon.

**Comment by xaque208** [comment]
https://github.com/voxpupuli/puppet-unbound/pull/222 is incomplete.  I'll come back.

**Comment by xaque208** [comment]
Hi @buzzdeee, I believe #222 will solve the issue, can you confirm?  Thanks for putting up the issue.

**Comment by buzzdeee** [comment]
@xaque208 
I tested #222 and it generally works for me. 
Only note: before that I had the stub IP address as a string, now it requires an Array due to the loop in the template.
The stub.pp still allows Array and String. So either the stub.pp needs to be more strict, or the template should be more relaxed.

**Comment by b4ldr** [comment]
this was fixed in #222
