### ISSUE TITLE
Please support 'respip' in module_config

### ISSUE THREAD

**Issue by hpkunz** [voxpupuli/puppet-unbound#250]
I would like to use the new rpz feature of unbound. however, in order to do so, I need to use the respip module, which is not in the list of allowed modules:

`Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Evaluation Error: Error while evaluating a Resource Statement, Class[Unbound]: parameter 'module_config' index 0 expects a match for Unbound::Module = Enum['cachedb', 'dns64', 'ipsecmod', 'iterator', 'python', 'subnetcache', 'validator'], got 'respip' (file: /etc/puppetlabs/code/environments/ifi/modules/profile/manifests/unbound.pp, line: 165, column: 3)`

adding 'respip' to the array in types/module.pp solves the problem.

Best,
Hp

**Comment by b4ldr** [comment]
@hpkunz sorry for the delay are you able to test [my RPZ branch](https://github.com/b4ldr/puppet-unbound/tree/rpz) used to create #259
