### ISSUE TITLE
add deprecation message on the forge

### ISSUE THREAD

**Issue by Dan33l** [voxpupuli/puppet-unbound#253]
For the moment, when i search unbound module on the Puppet forge, the module `zleslie-unbound` is listed. But it looks that module moved to VP.

I created a JIra issue asking for a deprecation message :
https://tickets.puppetlabs.com/browse/FORGE-577

**Comment by b4ldr** [comment]
@xaque208 may be useful to add a deprecation warning and pointer to puppet/unbound on forge

**Comment by Dan33l** [comment]
the deprecation message is now displayed on the Puppet forge.

**Comment by xaque208** [comment]
Oh thank you for handling this.  Much appreciated.

**Comment by xaque208** [comment]
More modules requested in https://tickets.puppetlabs.com/browse/FORGE-540
